feat: get compiled job specs from job_spec api
odpf/proton pull request #155
Opened 2022-07-06 04:27 UTC by Mryashbhardwaj

2022-07-17 10:06 UTC, sravankorumilli approved these changes

2022-07-17 10:06 UTC, sravankorumilli commented on odpf/optimus/core/v1beta1/job_run.proto
> +  // or set jonrun_id if this is a manual triggered execution
jobrun_id comment type

2022-07-17 11:25 UTC, sravankorumilli approved these changes

2022-07-17 11:30 UTC, sravankorumilli requested changes

2022-07-17 11:30 UTC, sravankorumilli commented on odpf/optimus/core/v1beta1/job_run.proto
> +  reserved 5;
if it  is just a rename lets not bother about backward compatibility imo as all the existing clients will still work.

2022-07-19 12:08 UTC, Mryashbhardwaj commented on odpf/optimus/core/v1beta1/job_run.proto
> +  // or set jonrun_id if this is a manual triggered execution
i could not understand this please

2022-08-11 07:24 UTC, sravankorumilli approved these changes

2022-08-11 07:25 UTC, merged

2022-08-11 07:25 UTC, Mryashbhardwaj commented on odpf/optimus/core/v1beta1/job_run.proto
> +  // or set jonrun_id if this is a manual triggered execution
fixed the typo issue